name: Build & Publish Docker image

on:
  push:
    branches: ["main"]      # build on main
    tags:     ["*"]        # and on version tags (v1.2.3)

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # ghcr.io/<owner>/<repo>

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read        # required for checkout
      packages: write       # required to push to ghcr

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # set up Buildx (modern Docker builder)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # generate tags and labels (latest, sha, version tag)
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      # log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build and push
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
